### ISSUE TITLE
20231004 Feedback

### ISSUE THREAD

**Issue by MisooKim2** [yugmldnjs/C202309#1]
워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week5/functionMulti
    - Warning: format specifies type 'int' but the argument has type 'long' [line 8]
    - Warning: format specifies type 'int' but the argument has type 'long' [line 9]
    - Warning: format specifies type 'int' but the argument has type 'long' [line 10]
        - 이유: 서식지정자 %d는 int 데이터를 위한 지정자입니다
        - 해결: %d를 %ld로 바꾸세요

**Comment by yugmldnjs** [comment]
functionMulti 파일에서 서식지정자 %d를 %ld로 변경 완료 했습니다.
